# Generated by Django 4.2.5 on 2023-09-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshopapp', '0005_alter_profile_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('text', models.TextField(max_length=3000)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
