# Generated by Django 4.2.5 on 2023-11-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshopapp', '0007_delete_news_article_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField()),
                ('promo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RotationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.IntegerField(default=1000000)),
            ],
        ),
    ]
